### ISSUE TITLE
`systemctl stop flexisip-b2bua` not responding

### ISSUE THREAD

**Issue by skhrshin** [BelledonneCommunications/flexisip#195] opened 2024-08-07 07:11 UTC
## Overview

flexisip-b2bua service does not respond to stop/restart.

## Environment

Flexisip 2.3.4 on Debian GNU/Linux bookworm

## Steps to reproduce

1. Start b2bua with `sudo systemctl start flexisip-b2bua`
2. Stop b2bua with `sudo systemctl stop flexisip-b2bua`

## Expected behavior

stop command returns.

## Actual behavior

stop command doesn't return.

## Remarks

As workaround, I modified `/lib/systemd/system/flexisip-b2bua.service` like following:

```
[Service]
#Type=forking
#ExecStart=/opt/belledonne-communications/bin/flexisip --server b2bua --daemon --syslog --pidfile /var/run/flexisip-b2bua.pid
ExecStart=/opt/belledonne-communications/bin/flexisip --server b2bua --syslog --pidfile /var/run/flexisip-b2bua.pid
```

**Comment by Failxxx** [comment] 2024-09-06 16:15
Hello @skhrshin,
Thank you for taking time to report a problem with Flexisip.

Indeed, we were able to reproduce your problem.
Fixed since e24342ed59bf24462ec4e270e65f0a5eb2eaae22.
It will be included in the next stable release: Flexisip 2.4

Sincerely,
Félix.

**Closed** 2024-12-06 13:55 UTC
