### ISSUE TITLE
Push Notification - No Key matching appId even while the matching appId exist

### ISSUE THREAD

**Issue by nikpakar** [BelledonneCommunications/flexisip#91] opened 2020-04-12 13:11 UTC
Dear All,

Im trying to get push notification working with flexisip and linphone android. FCM key setup done, flexisip pusher works fine.

But when the call invite tried to send the push, logs shows it says No key matching appId, but the registration of the desination phone as been registered with that appId

following is my log

2020-04-12 13:47:56:447 flexisip-debug-Restart SipEvent 0x55d445edf130
2020-04-12 13:47:56:447 flexisip-debug-Invoking onRequest() on module PushNotification
2020-04-12 13:47:56:448 flexisip-debug-No Key matching appId 929724111839

And following the contact header of the user registered in with this appId

SIP/2.0 200 Registration successful
Via: SIP/2.0/UDP xxxxxx:52887;branch=z9hG4bK.xys4LmusZ;rport=37402;received=43.250.242.64
From: <sip:2005@mydomain.net>;tag=BOPijrARU
To: <sip:2005@mydomain.net>;tag=a1Fm9HQ6meFrH
Call-ID: LZBnl5NqhH
CSeq: 21 REGISTER
Contact: <sip:2005@xxxx:37402;app-id=929724111839;pn-type=firebase;pn-timeout=0;pn-tok=cGGQkte3oDU:APA91bE91TWlJQTQJh67VglcvF7eUkKb-a3A-sSBOU
EuHEc8tEKO7w1qjUrqayBh_yPyXQnQ3WbFbmSqbaFKbtETJdO-z2ugHFr7yTE4diyo8no2WzGZGDfe8sUtXmlkjvet9WJL9Yjz;pn-silent=1>;+sip.instance="<urn:uuid:2d739bac-5c32
-00d0-badb-2439e8ac55cd>";+org.linphone.specs="lime";pub-gruu="sip:2005@mydomain.net;gr=urn:uuid:2d739bac-5c32-00d0-badb-2439e8ac55cd"
Expires: 3600
Server: Flexisip/_b57016d9dba5f3e427b31ba8cb7cd84399c140f8 (sofia-sip-nta/2.0)
Content-Length: 0

Can this be a some sort of bug in this version ? Im using the latest from git.

Thanks
-Nik

**Comment by 0x41mmarVM** [comment] 2020-04-13 14:06
The issue is more likely related to your api key not matching the app or project number being incorrect somewhere, perhaps double check the values? if that doesn't help, it could be helpful if you could supply output of the flexisip_pusher, with --debug

**Comment by Failxxx** [comment] 2024-11-22 13:44
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.

**Closed by Failxxx** 2024-11-22 13:44 UTC
